// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHfFBKREuMC0YIJ4caGcD1w94VUMeo14w',
    appId: '1:523234567617:web:ec191f422ceb7e498f7b40',
    messagingSenderId: '523234567617',
    projectId: 'hati-25259',
    authDomain: 'hati-25259.firebaseapp.com',
    storageBucket: 'hati-25259.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp4TA7ImMWxJTX8VYiMZGHNYyY6BWjZkw',
    appId: '1:523234567617:android:8a1e0609df7d96248f7b40',
    messagingSenderId: '523234567617',
    projectId: 'hati-25259',
    storageBucket: 'hati-25259.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_masoIb7todJM8VGatsHdS6_lKKBE084',
    appId: '1:523234567617:ios:9fdbf8ddb9e2856e8f7b40',
    messagingSenderId: '523234567617',
    projectId: 'hati-25259',
    storageBucket: 'hati-25259.firebasestorage.app',
    iosClientId: '523234567617-mlj5pksd0kv9dhm8r2lki7nsils7pj7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_masoIb7todJM8VGatsHdS6_lKKBE084',
    appId: '1:523234567617:ios:9fdbf8ddb9e2856e8f7b40',
    messagingSenderId: '523234567617',
    projectId: 'hati-25259',
    storageBucket: 'hati-25259.firebasestorage.app',
    iosClientId: '523234567617-mlj5pksd0kv9dhm8r2lki7nsils7pj7s.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHfFBKREuMC0YIJ4caGcD1w94VUMeo14w',
    appId: '1:523234567617:web:fcd2894c6b8b1aa68f7b40',
    messagingSenderId: '523234567617',
    projectId: 'hati-25259',
    authDomain: 'hati-25259.firebaseapp.com',
    storageBucket: 'hati-25259.firebasestorage.app',
  );
}
